# Generated by Django 4.2.3 on 2023-07-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advetisement',
            new_name='Advertisement',
        ),
    ]
